/* Generated by wayland-scanner 1.24.0 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface wl_output_interface;
extern const struct wl_interface zaether_ipc_output_v2_interface;

static const struct wl_interface *aether_ipc_unstable_v2_types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	&zaether_ipc_output_v2_interface,
	&wl_output_interface,
};

static const struct wl_message zaether_ipc_manager_v2_requests[] = {
	{ "release", "", aether_ipc_unstable_v2_types + 0 },
	{ "get_output", "no", aether_ipc_unstable_v2_types + 6 },
};

static const struct wl_message zaether_ipc_manager_v2_events[] = {
	{ "tags", "u", aether_ipc_unstable_v2_types + 0 },
	{ "layout", "s", aether_ipc_unstable_v2_types + 0 },
};

WL_PRIVATE const struct wl_interface zaether_ipc_manager_v2_interface = {
	"zaether_ipc_manager_v2", 2,
	2, zaether_ipc_manager_v2_requests,
	2, zaether_ipc_manager_v2_events,
};

static const struct wl_message zaether_ipc_output_v2_requests[] = {
	{ "release", "", aether_ipc_unstable_v2_types + 0 },
	{ "set_tags", "uu", aether_ipc_unstable_v2_types + 0 },
	{ "set_client_tags", "uu", aether_ipc_unstable_v2_types + 0 },
	{ "set_layout", "u", aether_ipc_unstable_v2_types + 0 },
	{ "quit", "2", aether_ipc_unstable_v2_types + 0 },
	{ "dispatch", "2ssssss", aether_ipc_unstable_v2_types + 0 },
};

static const struct wl_message zaether_ipc_output_v2_events[] = {
	{ "toggle_visibility", "", aether_ipc_unstable_v2_types + 0 },
	{ "active", "u", aether_ipc_unstable_v2_types + 0 },
	{ "tag", "uuuu", aether_ipc_unstable_v2_types + 0 },
	{ "layout", "u", aether_ipc_unstable_v2_types + 0 },
	{ "title", "s", aether_ipc_unstable_v2_types + 0 },
	{ "appid", "s", aether_ipc_unstable_v2_types + 0 },
	{ "layout_symbol", "s", aether_ipc_unstable_v2_types + 0 },
	{ "frame", "", aether_ipc_unstable_v2_types + 0 },
	{ "fullscreen", "2u", aether_ipc_unstable_v2_types + 0 },
	{ "floating", "2u", aether_ipc_unstable_v2_types + 0 },
	{ "x", "2i", aether_ipc_unstable_v2_types + 0 },
	{ "y", "2i", aether_ipc_unstable_v2_types + 0 },
	{ "width", "2i", aether_ipc_unstable_v2_types + 0 },
	{ "height", "2i", aether_ipc_unstable_v2_types + 0 },
	{ "last_layer", "2s", aether_ipc_unstable_v2_types + 0 },
	{ "kb_layout", "2s", aether_ipc_unstable_v2_types + 0 },
	{ "keymode", "2s", aether_ipc_unstable_v2_types + 0 },
	{ "scalefactor", "2u", aether_ipc_unstable_v2_types + 0 },
};

WL_PRIVATE const struct wl_interface zaether_ipc_output_v2_interface = {
	"zaether_ipc_output_v2", 2,
	6, zaether_ipc_output_v2_requests,
	18, zaether_ipc_output_v2_events,
};

